### PR TITLE
Fix new animations: use JS animations instead of CSS

### LINKED ISSUE #240: New animations are broken on Chrome Android
**Describe the bug**

They just does not work correctly

### PR DESCRIPTION
**Pull request by nathanaelhoun**
## Changes

- [x] New animations all uses JS animation (and not CSS animation as it behaves differently in other browsers)
- [x] Resized images to be 2* the final animation size. Allow to not have problem when the browser resizes the image.

Close #240

### CODE REVIEW

File: client/src/components/animations/AnimLoop.js [hunk 1]
```diff
@@ -1,28 +1,29 @@
 import { PropTypes } from "prop-types";
-import React from "react";
+import React, { useEffect, useState } from "react";
 
 const AnimationLoop = ({ imageLink, nbFrames, size, duration }) => {
-  const animationName = `animation-${imageLink.split("/").pop()}-${duration}`.replaceAll(".", "");
+  const [currentFrame, setCurrentFrame] = useState(0);
+
+  // At mount
```
Comment (nathanaelhoun) [inline client/src/components/animations/AnimLoop.js:7]:
```suggestion
  // Launch the animation interval at mount
```

**Review by FrancoisPog — COMMENTED** [review]
Great changes!
Even if the transitions may look more elegant with CSS, I personally find it more controlled and clearer to use JS!

**Review by FrancoisPog — APPROVED** [review]
Oops I forgot to approve
